//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.24 at 12:49:36 AM CEST 
//


package hu.zsdoma.timetracker.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hu.zsdoma.timetracker.tests.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Worklogs_QNAME = new QName("http://www.example.org/worklog", "worklogs");
    private final static QName _Worklog_QNAME = new QName("http://www.example.org/worklog", "worklog");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hu.zsdoma.timetracker.tests.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Worklog }
     * 
     */
    public Worklog createWorklog() {
        return new Worklog();
    }

    /**
     * Create an instance of {@link TimeTracker }
     * 
     */
    public TimeTracker createTimeTracker() {
        return new TimeTracker();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeTracker }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/worklog", name = "worklogs")
    public JAXBElement<TimeTracker> createWorklogs(TimeTracker value) {
        return new JAXBElement<TimeTracker>(_Worklogs_QNAME, TimeTracker.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Worklog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/worklog", name = "worklog")
    public JAXBElement<Worklog> createWorklog(Worklog value) {
        return new JAXBElement<Worklog>(_Worklog_QNAME, Worklog.class, null, value);
    }

}
