//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.24 at 12:49:36 AM CEST 
//


package hu.zsdoma.timetracker.schemas;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeTracker complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeTracker">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="worklogs" type="{http://www.example.org/worklog}Worklog" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="currentWorklog" type="{http://www.example.org/worklog}Worklog" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeTracker", propOrder = {
    "worklogs",
    "currentWorklog"
})
@XmlRootElement
public class TimeTracker {

    protected List<Worklog> worklogs;
    protected Worklog currentWorklog;

    /**
     * Gets the value of the worklogs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the worklogs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorklogs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Worklog }
     * 
     * 
     */
    public List<Worklog> getWorklogs() {
        if (worklogs == null) {
            worklogs = new ArrayList<Worklog>();
        }
        return this.worklogs;
    }

    /**
     * Gets the value of the currentWorklog property.
     * 
     * @return
     *     possible object is
     *     {@link Worklog }
     *     
     */
    public Worklog getCurrentWorklog() {
        return currentWorklog;
    }

    /**
     * Sets the value of the currentWorklog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Worklog }
     *     
     */
    public void setCurrentWorklog(Worklog value) {
        this.currentWorklog = value;
    }

}
